### ISSUE TITLE
Tips for Better SRT Translation and Word Learning

### ISSUE THREAD

**Issue by o-mo-ty** [Cerlancism/chatgpt-subtitle-translator#46]
I am translating an SRT file for a YouTube video (around 10 minutes long), but I occasionally make mistakes with the same words during translation, so I would like to improve by learning specific words.  
Is there a way to train the translation to handle such words better?

Additionally, I am using the following command to execute the translation, but if there’s a way to improve accuracy, please let me know:  
`cli/translator.mjs --from "English" --to "Japanese" --input "en.srt" --output "jp.srt" --model "gpt-4o"`

**Comment by Cerlancism** [comment]
Is your SRT file the one generated by YouTube?

**Comment by Cerlancism** [comment]
Any follow ups?

**Comment by o-mo-ty** [comment]
> Is your SRT file the one generated by YouTube?

Yes, that's correct. I'm using the SRT file downloaded from YouTube.

**Comment by Cerlancism** [comment]
Transcription from Youtube is not as good as Whisper. I recommend to use Whisper for transcription, particularly this one https://huggingface.co/spaces/aadnk/faster-whisper-webui/blob/main/README.md, you can run it on Google Colab if do not have a compatible GPU. 

However, all such transcriptions will have errors. You can reduce such errors by writing your own system instruction. The instruction can consist of the with the primary task of translation, the secondary task of correction, the "dictionary" you want to supply for "Word Learning".
```
Translate Japanese to English. 

**IMPORTANT**
Correct errors on character and cast member names, retain or reconstruct their nicknames where appropriate.

Here are the members with their character names and cast members, fix or correct mistakes in their names in transcription, and retain nicknames: 
```

Do note this can be expensive, so you might use the `gpt-4o-mini` instead of `gpt-4o`, as it I believe `gpt-4o-mini` is good enough for such translation tasks.

**Comment by o-mo-ty** [comment]
It's very clear. I'll give it a try.  
Thank you!
